'use client';
import Link from 'next/link';
import { useStore } from '@/lib/store';
import { ETT_REFERENCE_SUBJECTS, ETT_SCIENCE_UNITS, ETT_SYLLABUS_REFERENCE as reference } from '@/lib/data/ett-syllabus';
import { getQuestionPool } from '@/lib/data/question_bank_engine';

export default function EttSyllabus() {
  const { language, setLanguage } = useStore();
  const label = (en: string, hi: string, pa: string) => language === 'pa' ? pa : language === 'hi' ? hi : en;
  const available = getQuestionPool({ topicId: 'ett-light-reflection', examId: 'punjab-ett' }).length;
  return <main className="max-w-5xl mx-auto p-5 space-y-6 text-slate-200">
    <Link href="/syllabus/" className="text-teal-300 underline">← {label('All syllabi', 'सभी पाठ्यक्रम', 'ਸਾਰੇ ਪਾਠਕ੍ਰਮ')}</Link>
    <h1 className="text-2xl font-bold">{label('Punjab ETT: syllabus research', 'पंजाब ईटीटी: पाठ्यक्रम अनुसंधान', 'ਪੰਜਾਬ ਈਟੀਟੀ: ਪਾਠਕ੍ਰਮ ਖੋਜ')}</h1>
    <div className="flex gap-2" aria-label="Lesson language">{(['en', 'hi', 'pa'] as const).map(lang => <button key={lang} aria-pressed={language === lang} onClick={() => setLanguage(lang)} className={`rounded-lg px-4 py-2 ${language === lang ? 'bg-teal-700' : 'bg-slate-800'}`}>{lang === 'en' ? 'English' : lang === 'hi' ? 'हिंदी' : 'ਪੰਜਾਬੀ'}</button>)}</div>
    <section className="rounded-xl border border-amber-700 bg-amber-950/20 p-4 space-y-2">
      <h2 className="font-bold">{label('Upcoming notification pending', 'आगामी भर्ती की अधिसूचना लंबित', 'ਆਉਣ ਵਾਲੀ ਭਰਤੀ ਦੀ ਸੂਚਨਾ ਦੀ ਉਡੀਕ')}</h2>
      <p>{label('Reference: 5994-post recruitment, Paper B, document dated 1 December 2022. This is not confirmation of the upcoming exam pattern. Punjabi qualifying Paper A is separate; its revised notice and eligibility rules still need verification.', 'संदर्भ: 5994 पदों की भर्ती, पेपर B, 1 दिसंबर 2022 का दस्तावेज़। यह आगामी परीक्षा के पैटर्न की पुष्टि नहीं है। पंजाबी अर्हता पेपर A अलग है; संशोधित सूचना और पात्रता नियमों का सत्यापन बाकी है।', 'ਹਵਾਲਾ: 5994 ਅਸਾਮੀਆਂ ਦੀ ਭਰਤੀ, ਪੇਪਰ B, 1 ਦਸੰਬਰ 2022 ਦਾ ਦਸਤਾਵੇਜ਼। ਇਹ ਆਉਣ ਵਾਲੀ ਪ੍ਰੀਖਿਆ ਦੇ ਢਾਂਚੇ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਹੈ। ਪੰਜਾਬੀ ਯੋਗਤਾ ਪੇਪਰ A ਵੱਖਰਾ ਹੈ; ਸੋਧੀ ਸੂਚਨਾ ਅਤੇ ਯੋਗਤਾ ਨਿਯਮਾਂ ਦੀ ਜਾਂਚ ਬਾਕੀ ਹੈ।')}</p>
      <p className="text-sm">{label('Government publisher could not be reached on 8 October 2026. The available copy is hosted by a third party and remains provisional. Recruitment ETT and PSTET/D.El.Ed entrance are different exams.', '8 अक्टूबर 2026 को सरकारी प्रकाशक तक पहुँच नहीं बनी। उपलब्ध प्रति तीसरे पक्ष की वेबसाइट पर है और अभी अस्थायी संदर्भ है। ईटीटी भर्ती, पीएसटेट और डीएलएड प्रवेश अलग परीक्षाएँ हैं।', '8 ਅਕਤੂਬਰ 2026 ਨੂੰ ਸਰਕਾਰੀ ਪ੍ਰਕਾਸ਼ਕ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਬਣੀ। ਮੌਜੂਦ ਨਕਲ ਤੀਜੀ ਧਿਰ ਦੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਹੈ ਅਤੇ ਹਾਲੇ ਅਸਥਾਈ ਹਵਾਲਾ ਹੈ। ਈਟੀਟੀ ਭਰਤੀ, ਪੀਐੱਸਟੈੱਟ ਅਤੇ ਡੀਐੱਲਐੱਡ ਦਾਖ਼ਲਾ ਵੱਖਰੀਆਂ ਪ੍ਰੀਖਿਆਵਾਂ ਹਨ।')}</p>
      <div className="flex flex-wrap gap-4 text-teal-300 underline"><a href={reference.publisher} target="_blank" rel="noopener noreferrer">{label('Government recruitment portal', 'सरकारी भर्ती पोर्टल', 'ਸਰਕਾਰੀ ਭਰਤੀ ਪੋਰਟਲ')} ↗</a><a href={reference.mirror} target="_blank" rel="noopener noreferrer">{label('Archival PDF: third-party mirror', 'पुराना PDF: तीसरे पक्ष की प्रति', 'ਪੁਰਾਣਾ PDF: ਤੀਜੀ ਧਿਰ ਦੀ ਨਕਲ')} ↗</a></div>
    </section>
    <section className="space-y-3">
      <h2 className="text-xl font-bold">{label('Paper B subject index · archival total 200 marks', 'पेपर B विषय सूची · पुराने दस्तावेज़ में कुल 200 अंक', 'ਪੇਪਰ B ਵਿਸ਼ਾ ਸੂਚੀ · ਪੁਰਾਣੇ ਦਸਤਾਵੇਜ਼ ਵਿੱਚ ਕੁੱਲ 200 ਅੰਕ')}</h2>
      <p className="text-sm text-slate-400">{label('Subject marks are from the archival copy. They are not topic weights, question counts or a simulation of the upcoming exam.', 'विषय के अंक पुराने दस्तावेज़ से हैं। ये विषयांश का भार, प्रश्नों की संख्या या आगामी परीक्षा का अनुकरण नहीं हैं।', 'ਵਿਸ਼ਿਆਂ ਦੇ ਅੰਕ ਪੁਰਾਣੇ ਦਸਤਾਵੇਜ਼ ਤੋਂ ਹਨ। ਇਹ ਉਪਵਿਸ਼ਿਆਂ ਦਾ ਭਾਰ, ਸਵਾਲਾਂ ਦੀ ਗਿਣਤੀ ਜਾਂ ਆਉਣ ਵਾਲੀ ਪ੍ਰੀਖਿਆ ਦਾ ਨਮੂਨਾ ਨਹੀਂ ਹਨ।')}</p>
      {ETT_REFERENCE_SUBJECTS.map(subject => <article key={subject.name} className="rounded-lg border border-slate-700 p-3"><h3 className="font-semibold">{label(subject.name, subject.hi, subject.pa)} · {subject.marks}</h3><p className="text-sm text-slate-400">{subject.status}</p></article>)}
    </section>
    <section className="space-y-3">
      <h2 className="text-xl font-bold">{label('General Science → units → teaching subtopics', 'सामान्य विज्ञान → इकाइयाँ → अध्ययन उपविषय', 'ਆਮ ਵਿਗਿਆਨ → ਇਕਾਈਆਂ → ਅਧਿਐਨ ਉਪਵਿਸ਼ੇ')}</h2>
      <p className="text-sm text-slate-400">{label('25 unit headings appear on pages 1–2 of the archival copy. Subtopics below are ExamSathi’s teaching breakdown; they are not verbatim government requirements. Only the reflection lesson is added in this batch. Other subtopic lessons and banks remain pending.', 'पुरानी प्रति के पृष्ठ 1–2 में 25 इकाई शीर्षक हैं। नीचे के उपविषय ExamSathi का अध्ययन विभाजन हैं, सरकारी शब्दशः सूची नहीं। इस चरण में केवल परावर्तन का पाठ जोड़ा गया है। अन्य उपविषयों के पाठ और प्रश्न बैंक बाकी हैं।', 'ਪੁਰਾਣੀ ਨਕਲ ਦੇ ਸਫ਼ੇ 1–2 ਉੱਤੇ 25 ਇਕਾਈ ਸਿਰਲੇਖ ਹਨ। ਹੇਠਲੇ ਉਪਵਿਸ਼ੇ ExamSathi ਦੀ ਅਧਿਐਨ ਵੰਡ ਹਨ, ਸਰਕਾਰੀ ਸੂਚੀ ਦੇ ਅਸਲ ਸ਼ਬਦ ਨਹੀਂ। ਇਸ ਪੜਾਅ ਵਿੱਚ ਸਿਰਫ਼ ਪਰਾਵਰਤਨ ਦਾ ਪਾਠ ਜੋੜਿਆ ਗਿਆ ਹੈ। ਹੋਰ ਉਪਵਿਸ਼ਿਆਂ ਦੇ ਪਾਠ ਅਤੇ ਸਵਾਲ ਬੈਂਕ ਬਾਕੀ ਹਨ।')}</p>
      {ETT_SCIENCE_UNITS.map(([id, en, hi, pa, subtopics]) => <details key={id} open={id === 'light'} className="rounded-xl bg-slate-800 p-4"><summary className="cursor-pointer font-semibold text-teal-200">{label(en, hi, pa)}</summary><ul className="mt-3 space-y-3">{subtopics.map((subtopic, index) => <li key={subtopic} className="border-l-2 border-slate-600 pl-3">{id === 'light' && index === 0 ? <><Link href="/lesson/ett-light-reflection/?exam=punjab-ett" className="underline text-teal-300">{label('Reflection and plane mirrors', 'परावर्तन और समतल दर्पण', 'ਪਰਾਵਰਤਨ ਅਤੇ ਸਮਤਲ ਦਰਪਣ')}</Link><p className="text-sm my-2">{label('English, Hindi and Punjabi · 6 explanation sections · 6 flashcards · original practice, not verified PYQs', 'अंग्रेज़ी, हिंदी और पंजाबी · 6 व्याख्या खंड · 6 फ्लैशकार्ड · मौलिक अभ्यास, सत्यापित पुराने प्रश्न नहीं', 'ਅੰਗਰੇਜ਼ੀ, ਹਿੰਦੀ ਅਤੇ ਪੰਜਾਬੀ · 6 ਵਿਆਖਿਆ ਭਾਗ · 6 ਫਲੈਸ਼ਕਾਰਡ · ਮੌਲਿਕ ਅਭਿਆਸ, ਪ੍ਰਮਾਣਿਤ ਪੁਰਾਣੇ ਸਵਾਲ ਨਹੀਂ')} · {available}</p><div className="flex gap-4 text-teal-300">{[10, 20].filter(count => count <= available).map(count => <Link key={count} href={`/mock-test/topic-ett-light-reflection/?exam=punjab-ett&count=${count}`}>{count} {label('question mini mock', 'प्रश्नों का मिनी मॉक', 'ਸਵਾਲਾਂ ਦਾ ਮਿਨੀ ਮੌਕ')}</Link>)}</div></> : <><span>{subtopic}</span><p className="text-xs text-slate-400">{label('Lesson, translation and dedicated questions pending', 'पाठ, अनुवाद और विशेष प्रश्न बाकी', 'ਪਾਠ, ਅਨੁਵਾਦ ਅਤੇ ਖ਼ਾਸ ਸਵਾਲ ਬਾਕੀ')}</p></>}</li>)}</ul></details>)}
    </section>
    <p className="text-sm text-slate-400">{label('Next: verify the publisher copy and Paper A, transcribe the remaining five subjects, then complete one subtopic at a time. No full-syllabus coverage claim yet.', 'अगला चरण: सरकारी प्रति और पेपर A सत्यापित करें, बाकी पाँच विषयों की सूची निकालें, फिर एक-एक उपविषय पूरा करें। अभी पूरे पाठ्यक्रम को कवर करने का दावा नहीं है।', 'ਅਗਲਾ ਪੜਾਅ: ਸਰਕਾਰੀ ਨਕਲ ਅਤੇ ਪੇਪਰ A ਦੀ ਜਾਂਚ, ਬਾਕੀ ਪੰਜ ਵਿਸ਼ਿਆਂ ਦੀ ਸੂਚੀ, ਫਿਰ ਇੱਕ-ਇੱਕ ਉਪਵਿਸ਼ਾ ਪੂਰਾ ਕਰਨਾ। ਹਾਲੇ ਪੂਰਾ ਪਾਠਕ੍ਰਮ ਕਵਰ ਕਰਨ ਦਾ ਦਾਅਵਾ ਨਹੀਂ ਹੈ।')}</p>
  </main>;
}
